/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package signup;

import java.awt.Color;

/**
 *
 * @author Aditya
 */
public class Dashboard_History extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public String user;
    public databaseHandler database = new databaseHandler();
    public int maxTransactionDisplay =3;
    public int noOfTransactions;
    public Dashboard_History(String username) {
        initComponents();
        setBackground(new Color(0,0,0,0));
        user=username;
        jLabel1.setText(user);
        int userTransactions = database.countTransactions(username);
        if (userTransactions<=maxTransactionDisplay){
            noOfTransactions = userTransactions;
        }
        else{
            noOfTransactions = maxTransactionDisplay;
        }
        String[][] transactions = database.getTransactionData(username, noOfTransactions);
         for (int i = 0; i < transactions.length; i++) {
            for (int j = 0; j < transactions[i].length; j++) {
                System.out.print(transactions[i][j] + " ");
            }
            System.out.println();
         }
         
         if (noOfTransactions==1){
             card_white2.setVisible(false);
             card_white3.setVisible(false);
             T20.setVisible(false);
             T21.setVisible(false);
             T22.setVisible(false);
             T23.setVisible(false);
             T24.setVisible(false);
             
             T30.setVisible(false);
             T31.setVisible(false);
             T32.setVisible(false);
             T33.setVisible(false);
             T34.setVisible(false);
             
             T10.setText(transactions[0][0]);
             T11.setText(transactions[0][1]);
             T12.setText(transactions[0][2]);
             T13.setText(transactions[0][3]);
             T14.setText(transactions[0][4]);
             
         }
         else if (noOfTransactions==2){
             card_white3.setVisible(false);
             
             T30.setVisible(false);
             T31.setVisible(false);
             T32.setVisible(false);
             T33.setVisible(false);
             T34.setVisible(false);
             
             T10.setText(transactions[0][0]);
             T11.setText(transactions[0][1]);
             T12.setText(transactions[0][2]);
             T13.setText(transactions[0][3]);
             T14.setText(transactions[0][4]);
             
             T20.setText(transactions[1][0]);
             T21.setText(transactions[1][1]);
             T22.setText(transactions[1][2]);
             T23.setText(transactions[1][3]);
             T24.setText(transactions[1][4]);
             
         }
         else if (noOfTransactions==0){
             card_white1.setVisible(false);
             card_white2.setVisible(false);
             card_white3.setVisible(false);
             
             T30.setVisible(false);
             T31.setVisible(false);
             T32.setVisible(false);
             T33.setVisible(false);
             T34.setVisible(false);
             
             T20.setVisible(false);
             T21.setVisible(false);
             T22.setVisible(false);
             T23.setVisible(false);
             T24.setVisible(false);
             
             T10.setVisible(false);
             T11.setVisible(false);
             T12.setVisible(false);
             T13.setVisible(false);
             T14.setVisible(false);
         }
         else{
             T10.setText(transactions[0][0]);
             T11.setText(transactions[0][1]);
             T12.setText(transactions[0][2]);
             T13.setText(transactions[0][3]);
             T14.setText(transactions[0][4]);
             
             T20.setText(transactions[1][0]);
             T21.setText(transactions[1][1]);
             T22.setText(transactions[1][2]);
             T23.setText(transactions[1][3]);
             T24.setText(transactions[1][4]);
             
             T30.setText(transactions[2][0]);
             T31.setText(transactions[2][1]);
             T32.setText(transactions[2][2]);
             T33.setText(transactions[2][3]);
             T34.setText(transactions[2][4]);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new components.PanelBorder();
        background1 = new components.Background();
        jLabel2 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        card1 = new components.Card();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        card_white1 = new components.Card_white();
        T14 = new javax.swing.JLabel();
        T10 = new javax.swing.JLabel();
        T11 = new javax.swing.JLabel();
        T12 = new javax.swing.JLabel();
        T13 = new javax.swing.JLabel();
        card_white2 = new components.Card_white();
        T24 = new javax.swing.JLabel();
        T20 = new javax.swing.JLabel();
        T21 = new javax.swing.JLabel();
        T22 = new javax.swing.JLabel();
        T23 = new javax.swing.JLabel();
        card_white3 = new components.Card_white();
        T30 = new javax.swing.JLabel();
        T31 = new javax.swing.JLabel();
        T33 = new javax.swing.JLabel();
        T34 = new javax.swing.JLabel();
        T32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Credecio");

        kButton1.setText("Update Profile");
        kButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton1.setkBorderRadius(0);
        kButton1.setkEndColor(new Color(0,0,0,0));
        kButton1.setkHoverEndColor(new Color(0,0,0,50));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new Color(0,0,0,50));
        kButton1.setkStartColor(new Color(0,0,0,0));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setText("Log out");
        kButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton2.setkBorderRadius(0);
        kButton2.setkEndColor(new Color(0,0,0,0));
        kButton2.setkHoverEndColor(new Color(0,0,0,50));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new Color(0,0,0,50));
        kButton2.setkStartColor(new Color(0,0,0,0));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton3.setText("Check Balance");
        kButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton3.setkBorderRadius(0);
        kButton3.setkEndColor(new Color(0,0,0,0));
        kButton3.setkHoverEndColor(new Color(0,0,0,50));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new Color(0,0,0,50));
        kButton3.setkStartColor(new Color(0,0,0,0));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        kButton4.setText("Transfer");
        kButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton4.setkBorderRadius(0);
        kButton4.setkEndColor(new Color(0,0,0,0));
        kButton4.setkHoverEndColor(new Color(0,0,0,50));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverStartColor(new Color(0,0,0,50));
        kButton4.setkStartColor(new Color(0,0,0,0));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton5.setText("History");
        kButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton5.setkBorderRadius(0);
        kButton5.setkEndColor(new Color(0,0,0,0));
        kButton5.setkHoverEndColor(new Color(0,0,0,50));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverStartColor(new Color(0,0,0,50));
        kButton5.setkStartColor(new Color(0,0,0,0));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        kButton6.setText("Complaints");
        kButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton6.setkBorderRadius(0);
        kButton6.setkEndColor(new Color(0,0,0,0));
        kButton6.setkHoverEndColor(new Color(0,0,0,50));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverStartColor(new Color(0,0,0,50));
        kButton6.setkStartColor(new Color(0,0,0,0));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addComponent(kButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        panelBorder1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        kGradientPanel2.setAutoscrolls(true);
        kGradientPanel2.setkBorderRadius(15);
        kGradientPanel2.setkEndColor(new java.awt.Color(153, 255, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Time");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 50, -1));

        card1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("past transactions, empowering you to review and manage your spending patterns.");
        card1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Effortlessly track your financial journey with our Transaction History window. Dive into a comprehensive overview of your ");
        card1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        kGradientPanel2.add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 92, 950, 70));

        card_white1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T14.setForeground(new java.awt.Color(255, 255, 255));
        T14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T14.setText("jLabel11");
        card_white1.add(T14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 83, -1));

        T10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T10.setForeground(new java.awt.Color(255, 255, 255));
        T10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T10.setText("jLabel11");
        card_white1.add(T10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 83, -1));

        T11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T11.setForeground(new java.awt.Color(255, 255, 255));
        T11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T11.setText("jLabel11");
        card_white1.add(T11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 83, -1));

        T12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T12.setForeground(new java.awt.Color(255, 255, 255));
        T12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T12.setText("jLabel11");
        card_white1.add(T12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 83, -1));

        T13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T13.setForeground(new java.awt.Color(255, 255, 255));
        T13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T13.setText("jLabel11");
        card_white1.add(T13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 83, -1));

        kGradientPanel2.add(card_white1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 930, 100));

        card_white2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T24.setForeground(new java.awt.Color(255, 255, 255));
        T24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T24.setText("jLabel11");
        card_white2.add(T24, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 83, -1));

        T20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T20.setForeground(new java.awt.Color(255, 255, 255));
        T20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T20.setText("jLabel11");
        card_white2.add(T20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 83, -1));

        T21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T21.setForeground(new java.awt.Color(255, 255, 255));
        T21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T21.setText("jLabel11");
        card_white2.add(T21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 83, -1));

        T22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T22.setForeground(new java.awt.Color(255, 255, 255));
        T22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T22.setText("jLabel11");
        card_white2.add(T22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 83, -1));

        T23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T23.setForeground(new java.awt.Color(255, 255, 255));
        T23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T23.setText("jLabel11");
        card_white2.add(T23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 83, -1));

        kGradientPanel2.add(card_white2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 930, 100));

        T30.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T30.setForeground(new java.awt.Color(255, 255, 255));
        T30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T30.setText("jLabel11");

        T31.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T31.setForeground(new java.awt.Color(255, 255, 255));
        T31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T31.setText("jLabel11");

        T33.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T33.setForeground(new java.awt.Color(255, 255, 255));
        T33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T33.setText("jLabel11");

        T34.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T34.setForeground(new java.awt.Color(255, 255, 255));
        T34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T34.setText("jLabel11");

        T32.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        T32.setForeground(new java.awt.Color(255, 255, 255));
        T32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T32.setText("jLabel11");

        javax.swing.GroupLayout card_white3Layout = new javax.swing.GroupLayout(card_white3);
        card_white3.setLayout(card_white3Layout);
        card_white3Layout.setHorizontalGroup(
            card_white3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_white3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(T30, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(T31, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addComponent(T33, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(T34, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(card_white3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(card_white3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(T32, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        card_white3Layout.setVerticalGroup(
            card_white3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_white3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(card_white3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T30)
                    .addComponent(T31)
                    .addComponent(T33)
                    .addComponent(T34))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(card_white3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(card_white3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(T32)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        kGradientPanel2.add(card_white3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("Transaction History");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 26, 290, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 102));
        jLabel7.setText("ID");
        kGradientPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 40, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setText("Recipient");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 100, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 102));
        jLabel9.setText("Amount");
        kGradientPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 90, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 102));
        jLabel10.setText("Date");
        kGradientPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 50, -1));

        panelBorder1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 1010, 660));

        kGradientPanel1.setkBorderRadius(15);
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("UserName");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(915, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelBorder1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1010, 70));

        getContentPane().add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        Dashboard_Balance balance = new Dashboard_Balance(user);
        balance.setLocationRelativeTo(null);
        balance.setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        Dashboard_Profile profile = new Dashboard_Profile(user);
        profile.setLocationRelativeTo(null);
        profile.setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        Dashboard_Transfer transfer = new Dashboard_Transfer(user);
        transfer.setLocationRelativeTo(null);
        transfer.setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        Dashboard_Complaint complaint = new Dashboard_Complaint(user);
        complaint.setLocationRelativeTo(null);
        complaint.setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        SignUp sig = new SignUp();
        sig.setLocationRelativeTo(null); // Centering the Login frame on the screen
        sig.setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel T10;
    private javax.swing.JLabel T11;
    private javax.swing.JLabel T12;
    private javax.swing.JLabel T13;
    private javax.swing.JLabel T14;
    private javax.swing.JLabel T20;
    private javax.swing.JLabel T21;
    private javax.swing.JLabel T22;
    private javax.swing.JLabel T23;
    private javax.swing.JLabel T24;
    private javax.swing.JLabel T30;
    private javax.swing.JLabel T31;
    private javax.swing.JLabel T32;
    private javax.swing.JLabel T33;
    private javax.swing.JLabel T34;
    private components.Background background1;
    private components.Card card1;
    private components.Card_white card_white1;
    private components.Card_white card_white2;
    private components.Card_white card_white3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private components.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
